In [1]:
import pandas as pd

In [2]:
snow_df = pd.read_csv('snow_food.csv')
snow_df

       단어     식품대분류명  에너지(kcal)  단백질(g)  빈도수  날씨구분
0      커피    음료 및 차류          3    0.33  160  snow
1      치킨        튀김류        257   17.17   56  snow
2     칼국수    면 및 만두류         77    3.30   44  snow
3      라떼    음료 및 차류         56    2.82   44  snow
4      피자    빵 및 과자류        274   10.68   40  snow
..    ...        ...        ...     ...  ...   ...
203  곤드레밥         밥류         87    2.09    1  snow
204   부추전  전·적 및 부침류        167    4.63    1  snow
205  두부부침  전·적 및 부침류        140   10.92    1  snow
206  제육볶음        볶음류        195   12.15    1  snow
207  치킨까스        튀김류        296   13.96    1  snow

[208 rows x 6 columns]

In [3]:
rain_df = pd.read_csv('rain_food.csv')
rain_df

       단어     식품대분류명  에너지(kcal)  단백질(g)  빈도수  날씨구분
0     칼국수    면 및 만두류         77    3.30  399  rain
1     수제비    면 및 만두류         58    2.31  126  rain
2      짬뽕    면 및 만두류         58    2.79   81  rain
3      파전  전·적 및 부침류        171    5.50   79  rain
4      커피    음료 및 차류          3    0.33   69  rain
..    ...        ...        ...     ...  ...   ...
192   무조림        조림류         48    2.26    1  rain
193   비빔면    면 및 만두류        153    5.70    1  rain
194  비빔국수    면 및 만두류        113    3.40    1  rain
195    팥죽    죽 및 스프류         81    3.17    1  rain
196    쿠키    빵 및 과자류        309    3.36    1  rain

[197 rows x 6 columns]

In [4]:
rainsnow_df = pd.concat([rain_df,snow_df])

In [5]:
rainsnow = rainsnow_df.drop_duplicates(['단어'], keep='first')

In [6]:
rainsnow['날씨구분'] = 'rainsnow'

<ipython-input-6-2648df841bf0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rainsnow['날씨구분'] = 'rainsnow'

In [7]:
rainsnow.to_csv('rainsnow.csv',index=False)

In [8]:
df = pd.read_csv('rainsnow.csv')
df

        단어     식품대분류명  에너지(kcal)  단백질(g)  빈도수      날씨구분
0      칼국수    면 및 만두류         77    3.30  399  rainsnow
1      수제비    면 및 만두류         58    2.31  126  rainsnow
2       짬뽕    면 및 만두류         58    2.79   81  rainsnow
3       파전  전·적 및 부침류        171    5.50   79  rainsnow
4       커피    음료 및 차류          3    0.33   69  rainsnow
..     ...        ...        ...     ...  ...       ...
267    회덮밥         밥류        145    9.10    1  rainsnow
268    명란젓        젓갈류        147   17.96    1  rainsnow
269   충무김밥         밥류        146    5.86    1  rainsnow
270  돌솥비빔밥         밥류         86    2.81    1  rainsnow
271   치킨까스        튀김류        296   13.96    1  rainsnow

[272 rows x 6 columns]